data_pack:
  load: .
  min_format: [107,1]
  max_format: [107,1]

pipeline:
  - mecha

"description": [
  {"text":"\u2601 Bound \u2601", "color":"#47cbff"},
  {"text":"\n"},
  {"text":"A triple jump enchantment","color":"#7e7e7e"}
]